# ./.circleci/config.yml

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          command: sudo npm i -g npm

      - run:
          name: Report versions
          command: node --version && npm --version && lsb_release -a

      # Restore cached dependencies
      - restore_cache:
          keys:
            # We should not have branches with radically different dependencies
            # so {{ .Branch }} is redundant
            - dependency-cache-{{ checksum "package-lock.json" }}
            # Fallback to using the latest cache if no exact match is found
            - dependency-cache

      # Install dependencies the way a user does (i.e. not using npm ci)
      - run:
          name: Install dependencies
          command: npm install

      # Update cached dependencies
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm run test
